# Package Overview
package_name: bankloan_model

# Data Files
training_data_file: loan_data.csv

# Variables
target: loan_status

pipeline_name: bankloan_model
pipeline_save_file: bankloan__model_output_v

# Features that will go inside processing pipeline
features:
  - person_age
  - person_gender
  - person_education
  - person_income
  - person_emp_exp
  - person_home_ownership
  - loan_amnt
  - loan_intent
  - loan_int_rate
  - cb_person_cred_hist_length
  - credit_score
  - previous_loan_defaults_on_file

unused_fields:
  - loan_status
  - loan_percent_income


# Features names

age: person_age
gender: person_gender
education: person_education
income: person_income
emp_experience: person_emp_exp
home_type: person_home_ownership
loan_amount: loan_amnt
intent_var: loan_intent #Use OHE for unbiased results
interest_rate: loan_int_rate
credit_history_lenght: cb_person_cred_hist_length
creditscore_var: credit_score
previous_loan_defaults: previous_loan_defaults_on_file

# Mappings for Ordinal categorical features

gender_mappings: 
  female: 0
  male: 1

education_mappings: 
  Master: 0
  High School: 1
  Bachelor: 2
  Associate: 3
  Doctorate: 4


home_type_mappings:
  RENT: 0
  MORTAGAGE: 1
  OWN: 2
  OTHER: 3

previous_loan_defaults_mappings:
  Yes: 0
  No: 1

  
# Set train/test split
test_size: 0.20

#Model Parameters
random_state: 0